In [1]:
from selenium import webdriver
driver = webdriver.Chrome() 
driver.get('https://shopee.tw/')

In [6]:
c=';'.join(['{}={}'.format(item.get('name'),item.get('value')) for item in driver.get_cookies()])

In [7]:
token= [item.get('value') for item in driver.get_cookies() if item.get('name')=='csrftoken'][0]

In [8]:
import requests
import json 
jd=json.loads('{"item_shop_ids":[{"itemid":36764703,"adsid":0,"shopid":3563503,"campaignid":0},{"itemid":38588654,"adsid":0,"shopid":3783503,"campaignid":0},{"itemid":65841760,"adsid":0,"shopid":4811828,"campaignid":0},{"itemid":65399318,"adsid":0,"shopid":1464046,"campaignid":0},{"itemid":129870030,"adsid":0,"shopid":3606232,"campaignid":0},{"itemid":39849898,"adsid":0,"shopid":6071543,"campaignid":0},{"itemid":36359135,"adsid":0,"shopid":3911448,"campaignid":0},{"itemid":99594103,"adsid":0,"shopid":8545055,"campaignid":0},{"itemid":35779990,"adsid":0,"shopid":3563503,"campaignid":0},{"itemid":65897385,"adsid":0,"shopid":4811828,"campaignid":0},{"itemid":97540572,"adsid":0,"shopid":5589980,"campaignid":0},{"itemid":18180652,"adsid":0,"shopid":3127332,"campaignid":0},{"itemid":38684775,"adsid":0,"shopid":2922951,"campaignid":0},{"itemid":59509279,"adsid":0,"shopid":2907398,"campaignid":0},{"itemid":166947120,"adsid":0,"shopid":2526438,"campaignid":0},{"itemid":16107540,"adsid":0,"shopid":4681700,"campaignid":0},{"itemid":104044522,"adsid":0,"shopid":3963847,"campaignid":0},{"itemid":75861803,"adsid":0,"shopid":3052942,"campaignid":0},{"itemid":21291010,"adsid":0,"shopid":4664869,"campaignid":0},{"itemid":190214026,"adsid":0,"shopid":6285856,"campaignid":0},{"itemid":50228486,"adsid":0,"shopid":4925750,"campaignid":0},{"itemid":111218672,"adsid":0,"shopid":3963847,"campaignid":0},{"itemid":37636633,"adsid":0,"shopid":1060221,"campaignid":0},{"itemid":38118940,"adsid":0,"shopid":6071543,"campaignid":0},{"itemid":13272058,"adsid":0,"shopid":4314111,"campaignid":0},{"itemid":43111262,"adsid":0,"shopid":4337884,"campaignid":0},{"itemid":11033679,"adsid":0,"shopid":1459710,"campaignid":0},{"itemid":79714127,"adsid":0,"shopid":11331334,"campaignid":0},{"itemid":34147015,"adsid":0,"shopid":4387763,"campaignid":0},{"itemid":23373391,"adsid":0,"shopid":852152,"campaignid":0},{"itemid":91369724,"adsid":0,"shopid":8709912,"campaignid":0},{"itemid":131833447,"adsid":0,"shopid":107735,"campaignid":0},{"itemid":68251588,"adsid":0,"shopid":7582848,"campaignid":0},{"itemid":113600643,"adsid":0,"shopid":7559477,"campaignid":0},{"itemid":135962686,"adsid":0,"shopid":16087157,"campaignid":0},{"itemid":129320212,"adsid":0,"shopid":7904588,"campaignid":0},{"itemid":181285130,"adsid":0,"shopid":1333499,"campaignid":0},{"itemid":135188247,"adsid":0,"shopid":5746832,"campaignid":0},{"itemid":166625542,"adsid":0,"shopid":2429502,"campaignid":0},{"itemid":246258666,"adsid":0,"shopid":16696353,"campaignid":0},{"itemid":47622897,"adsid":0,"shopid":3787331,"campaignid":0},{"itemid":39624139,"adsid":0,"shopid":3818723,"campaignid":0},{"itemid":46910255,"adsid":0,"shopid":2192976,"campaignid":0},{"itemid":138227072,"adsid":0,"shopid":7972250,"campaignid":0},{"itemid":90605478,"adsid":0,"shopid":334932,"campaignid":0},{"itemid":103692528,"adsid":0,"shopid":12238,"campaignid":0},{"itemid":68344251,"adsid":0,"shopid":5305151,"campaignid":0},{"itemid":40110748,"adsid":0,"shopid":7582848,"campaignid":0},{"itemid":120340449,"adsid":0,"shopid":7789706,"campaignid":0},{"itemid":113453806,"adsid":0,"shopid":2830501,"campaignid":0}]}')

headers={ 
'accept':'application/json',
'Accept-Encoding':'gzip, deflate, br',
'Accept-Language':'zh-TW,zh;q=0.8,en-US;q=0.6,en;q=0.4',
'Connection':'keep-alive',
'Content-Length':'3134',
'content-type':'application/json',
'Cookie':c,
'Host':'shopee.tw',
'Origin':'https://shopee.tw',
'Referer':'https://shopee.tw/search/?keyword=%E8%80%81%E6%A5%8A',
'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
'x-csrftoken':token
}
res=requests.post('https://shopee.tw/api/v1/items/',json=jd,headers=headers)
res

In [10]:
import pandas
df=pandas.DataFrame(res.json())
df

,attributes,brand,can_use_wholesale,catid,cb_option,cmt_count,coin_earn_items,coin_spend_cash_unit,condition,currency,...,rcount_with_image,shopid,show_discount,show_free_shipping,sold,stock,sub_catid,third_catid,videos,wholesale_tier_list
0,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",老楊,False,66,0,4496,None,None,5,TWD,...,8,3563503,0,False,1023,341,2209,8394,[],[]
1,[],,False,66,0,70,None,None,1,TWD,...,0,3783503,0,True,16,3,2209,8394,[],[]
2,[],,False,66,0,998,None,None,1,TWD,...,2,4811828,0,False,146,74,2209,8394,[],[]
3,"[{'id': 5541, 'value': '老楊', 'is_timestamp': F...",老楊,False,66,0,51,None,None,1,TWD,...,0,1464046,0,True,42,45,2209,8394,[],[]
4,[],,False,66,0,29,None,None,1,TWD,...,0,3606232,0,False,11,2468,290,5811,[],[]
5,[],,False,66,0,356,None,None,5,TWD,...,0,6071543,0,False,65,134,2209,8393,[],[]
6,[],,False,66,0,477,None,None,1,TWD,...,1,3911448,5,True,17,9,2209,8394,[],[]
7,"[{'id': 4911, 'value': '', 'is_timestamp': Fal...",,False,66,0,190,None,None,1,TWD,...,1,8545055,0,False,39,600,2209,8394,[],[]
8,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",老楊,False,66,0,748,None,None,5,TWD,...,2,3563503,0,False,111,113,2209,8394,[],[]
9,[],,False,66,0,422,None,None,1,TWD,...,1,4811828,0,False,99,91,2209,8394,[],[]
10,[],老楊,False,66,0,490,None,None,1,TWD,...,7,5589980,0,True,206,4089,2209,8394,[],[]
11,"[{'id': 4918, 'value': '', 'is_timestamp': Fal...",,True,66,0,111,None,None,1,TWD,...,1,3127332,0,True,443,636,2209,5815,[],"[{'min_count': 10, 'price': 8600000, 'max_coun..."
12,[],,False,66,0,253,None,None,1,TWD,...,0,2922951,0,False,16,258,2209,8394,[],[]
13,[],,False,66,0,981,None,None,1,TWD,...,1,2907398,0,False,97,1629,2209,8394,[],[]
14,"[{'id': 4868, 'value': '台灣', 'is_timestamp': F...",,False,66,0,12,None,None,1,TWD,...,0,2526438,0,True,13,382,1647,8385,[],[]
15,[],,False,66,0,17,None,None,1,TWD,...,0,4681700,0,True,2,59,2209,5815,[],[]
16,[],,False,66,0,6,None,None,1,TWD,...,0,3963847,0,False,3,4,1647,8385,[],[]
17,[],,False,66,0,21,None,None,1,TWD,...,0,3052942,0,True,4,106,2209,8394,[],[]
18,[],,False,66,0,81,None,None,1,TWD,...,0,4664869,0,False,15,7,2209,8394,[],[]
19,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",,True,66,0,22,None,None,0,TWD,...,0,6285856,0,False,59,117,2209,8394,[],"[{'min_count': 10, 'price': 8900000}]"
20,"[{'id': 4911, 'value': '', 'is_timestamp': Fal...",,False,66,0,71,None,None,1,TWD,...,0,4925750,0,False,6,299,2209,8394,[],[]
21,[],,False,66,0,4,None,None,1,TWD,...,0,3963847,0,False,2,17,1647,8385,[],[]
22,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",老楊鹹蛋黃,False,66,0,1152,None,None,1,TWD,...,2,1060221,0,True,4,32,2209,8394,[],[]
23,[],,False,66,0,172,None,None,5,TWD,...,0,6071543,0,False,6,793,2209,8393,[],[]
24,[],,False,66,0,190,None,None,1,TWD,...,0,4314111,0,True,6,4,2209,5815,[],[]
25,[],老楊,False,66,0,78,None,None,1,TWD,...,0,4337884,0,True,10,248,2209,8394,[],[]
26,"[{'id': 4875, 'value': '', 'is_timestamp': Fal...",,False,66,0,186,None,None,1,TWD,...,0,1459710,0,True,8,10,1647,5817,[],[]
27,[],,False,66,0,37,None,None,5,TWD,...,0,11331334,0,False,12,68,290,5811,[],[]
28,"[{'id': 1501, 'value': '老楊', 'is_timestamp': F...",老楊,False,66,0,34,None,None,1,TWD,...,0,4387763,0,False,5,122,2209,8394,[],[]
29,"[{'id': 4918, 'value': '', 'is_timestamp': Fal...",『好慈a柑仔店』,False,66,0,56,None,None,5,TWD,...,1,852152,0,False,3,21,2209,5815,[],[]
30,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",老楊,False,66,0,5,None,None,1,TWD,...,0,8709912,0,False,1,3,2209,8394,[],[]
31,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",老楊,False,66,0,9,None,None,0,TWD,...,0,107735,0,False,6,6,2209,8394,[],[]
32,[],,False,66,0,28,None,None,1,TWD,...,0,7582848,0,True,4,21,2209,8394,[],[]
33,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",,False,66,0,5,None,None,-1,TWD,...,0,7559477,0,True,5,183,2209,8394,[],[]
34,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",糖果餅乾屋,False,66,0,9,None,None,-1,TWD,...,0,16087157,0,True,3,468,2209,8394,[],[]
35,"[{'id': 4911, 'value': '', 'is_timestamp': Fal...",,False,66,0,2,None,None,1,TWD,...,0,7904588,0,False,6,9,2209,8394,[],[]
36,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",,False,66,0,1,None,None,0,TWD,...,0,1333499,12,False,4,22,2209,8394,[],[]
37,[],,False,66,0,1,None,None,1,TWD,...,0,5746832,0,False,4,12,1647,8385,[],[]
38,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",老楊,False,66,0,4,None,None,1,TWD,...,0,2429502,0,False,7,7,2209,8394,[],[]
39,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",寶島零食,False,66,0,1,None,None,-1,TWD,...,0,16696353,0,False,10,12,2209,8394,[],[]
40,"[{'id': 4911, 'value': '', 'is_timestamp': Fal...",,False,66,0,33,None,None,1,TWD,...,0,3787331,0,False,2,2,2209,8394,[],[]
41,[],,False,66,0,86,None,None,1,TWD,...,0,3818723,0,False,2,78,2209,8394,[],[]
42,[],,False,66,0,17,None,None,5,TWD,...,0,2192976,0,True,2,8,2209,8394,[],[]
43,[],,False,66,0,6,None,None,1,TWD,...,0,7972250,0,True,1,4,290,5811,[],[]
44,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",老楊,False,66,0,13,None,None,1,TWD,...,0,334932,0,False,1,297,2209,8394,[],[]
45,"[{'id': 4911, 'value': '', 'is_timestamp': Fal...",,False,66,0,9,None,None,1,TWD,...,0,12238,0,True,1,160,2209,8394,[],[]
46,"[{'id': 4911, 'value': '一般', 'is_timestamp': F...",,False,66,0,72,None,None,1,TWD,...,1,5305151,0,False,2,774,2209,8394,[],[]
47,"[{'id': 4817, 'value': '', 'is_timestamp': Fal...",,False,66,0,6,None,None,1,TWD,...,0,7582848,0,True,3,11,1649,5819,[],[]
48,"[{'id': 4868, 'value': '台灣', 'is_timestamp': F...",,False,66,0,9,None,None,0,TWD,...,0,7789706,0,True,1,16,1647,8385,[],[]
49,"[{'id': 4911, 'value': '', 'is_timestamp': Fal...",,False,66,0,4,None,None,1,TWD,...,0,2830501,0,False,2,27,2209,8394,[],[]